permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_call:
    inputs:
      jfrog-platform-url:
        type: string
        description: "JFrog platform URL"
        required: false
        default: https://aerospike.jfrog.io
      java-version:
        type: string
        required: true
      is-snapshot:
        type: string
        required: true
      release-version:
        type: string
        required: true
    secrets:
      JFROG_OIDC_PROVIDER:
        required: true
      JFROG_OIDC_AUDIENCE:
        required: true

jobs:
  build:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Set up JFrog credentials l
        id: setup-jfrog-cli
        uses: jfrog/setup-jfrog-cli@5b06f730cc5a6f55d78b30753f8583454b08c0aa # v4.8.1
        env:
          JF_URL: ${{ inputs.jfrog-platform-url }}
          JF_PROJECT: clients
        with:
          version: 2.72.2
          oidc-provider-name: ${{ secrets.JFROG_OIDC_PROVIDER }}
          oidc-audience: ${{ secrets.JFROG_OIDC_AUDIENCE }}

      - shell: bash
        run: |
          echo "IS_SNAPSHOT=${{ inputs.is-snapshot }}" >> $GITHUB_ENV

      - name: Aggregate builds
        run: |
          # record env variables 
          jf rt bce clients-java-push-to-dev ${{ github.run_number }}

          jf rt ba clients-java-push-to-dev ${{ github.run_number }} clients-java-push-to-dev_aerospike-client-bc-jdk${{ inputs.java-version }} ${{ github.run_number }}
          jf rt ba clients-java-push-to-dev ${{ github.run_number }} clients-java-push-to-dev_aerospike-client-jdk${{ inputs.java-version }} ${{ github.run_number }}

          jf rt bp clients-java-push-to-dev ${{ github.run_number }}

      - name: Install sponge
        run: sudo apt install -y moreutils

      - name: Create file spec for release bundle
        shell: bash
        working-directory: .github/workflows
        run: | 
          cat ./rb-spec.json | jq '.files[0].build = "clients-java-push-to-dev/${{ github.run_number }}"' | sponge ./rb-spec.json

      - name: Create release bundle from JFrog build
        working-directory: ./.github/workflows
        run: | 
          jf rbc --spec=./rb-spec.json clients-java-jdk${{ inputs.java-version }} ${{ inputs.release-version}}

      - name: Promote release bundle to DEV stage
        run: | 
          jf rbp --signing-key=aerospike clients-java-jdk${{ inputs.java-version }} ${{ inputs.release-version}} DEV