on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      build-number:
        type: string
        required: true

jobs:
  debug-job:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: debug
        run: |
          echo "${{ inputs.ref }}"
          echo "${{ github.base_ref }}"

  pre-requisites:
    needs: debug-job
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    outputs:
      java-version: ${{ steps.get-java-version.outputs.java-version }}
      is-snapshot: ${{ steps.get-version.outputs.is-snapshot }}
      release-version: ${{ steps.get-version.outputs.release-version }}
    steps:
      - name: Checkout client
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      # Fetching java version used in this build. The java version is set in pom file  and could vary between builds.
      - name: Get java version
        id: get-java-version
        run: |
          echo java-version="$(grep '<java.version>' pom.xml | sed -e 's/<[^>]*>//g' | awk '{$1=$1};1' | sed 's/^1\.8$/8/')"  >> $GITHUB_OUTPUT

      - name: Debug - java-version
        run: |
          echo ${{ steps.get-java-version.outputs.java-version }}

      - name: Get version
        id: get-version
        uses: ./.github/actions/get-version

  build:
    uses: ./.github/workflows/release.yaml
    needs: pre-requisites
    strategy:
      matrix:
        crypto-type: [bouncycastle, gnu]
    with:
      ref: ${{ inputs.ref }}
      java-version: ${{ needs.pre-requisites.outputs.java-version }}
      crypto-type: ${{ matrix.crypto-type }}
      is-snapshot: ${{ needs.pre-requisites.outputs.is-snapshot }}
    secrets: inherit

  aggregate-published-artifacts:
    uses: ./.github/workflows/aggregate-build.yaml
    needs: [pre-requisites, build]
    secrets: inherit
    with:
      java-version: ${{ needs.pre-requisites.outputs.java-version }}
      is-snapshot: ${{ needs.pre-requisites.outputs.is-snapshot }}
      release-version: ${{ needs.pre-requisites.outputs.release-version }}
